### ISSUE TITLE
need to call context.signalRenderComplete(); when return on error 

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/spotfire-mods#27]
If context.signalRenderComplete(); is not called when return on error, the visualization with error message in it would take about 20 seconds to be export as png/pdf or generated preview for pdf.

Here is sample code from js-dev-barchart

        let dataViewYAxis = await dataView.continuousAxis("Y");
        if (dataViewYAxis == null) {
            mod.controls.errorOverlay.show("No data on y axis.", "y");
            context.signalRenderComplete();    // add this line is necessary
            return;
        } else {
            mod.controls.errorOverlay.hide("y");
        }

**Comment by objerke** [comment]
Thanks for reporting this. This is definitely something that could be improved in the examples. 

@ebrandin, I think an alternative solution to this problem would be to implicitly call signalRenderComplete when an error overlay has been displayed, since nothing else will render to screen. What do you think?

**Comment by ebrandin** [comment]
I agree @objerke, it would be a nice addition to the API to not require signalRenderComplete when an error overlay is shown.

**Comment by objerke** [comment]
We aim to fix this at an API level in a future Spotfire release.
