### ISSUE TITLE
Documentation about how to use PopOut

### ISSUE THREAD

**Issue by hski-github** [TIBCOSoftware/spotfire-mods#40]
Would be great to have some documentation and examples collected and references around use of [PopOut](https://tibcosoftware.github.io/spotfire-mods/api-docs/interfaces/popout.html) similar to what is written how to use the mod data view in a wiki page in the [official documentation location](https://tibcosoftware.github.io/spotfire-mods/docs/using-the-api/) 

Also [PopoutComponentFactory](https://tibcosoftware.github.io/spotfire-mods/api-docs/interfaces/popoutcomponentfactory.html) supports only button, check and radio, while I would also require text and textarea input field for my mod and would wonder if I can define custom PopoutComponent (and by that not need to wait for new API version which support text and textarea).

**Comment by objerke** [comment]
Thanks for your documentation suggestion @hski-github. 

The current components in the `PopoutComponentFactory` are the only ones available at the moment. It is not possible to create custom components since the components are rendered outside of the mod sandbox. 

The input field is listed as an idea in the idea portal [here](https://ideas.tibco.com/ideas/TS-I-8057). Please feel free to vote for it.
