### ISSUE TITLE
Question: Possibility to call XMLHttpRequest from within Mod

### ISSUE THREAD

**Issue by hski-github** [TIBCOSoftware/spotfire-mods#79]
In the Mods manifest you can register external resources. Are these URLs are allowed for XMLHttpRequest calls from within JavaScript code of the Mod? Or is this blocked by the Mods framework?

**Comment by objerke** [comment]
Yes, you are allowed to make `XMLHttpRequest` calls to external resources. You can add URLs in the top level property `externalResources` (`string[]`) in the `mod-manifest.json`. This will allow the mod to make Ajax or other kinds of calls to those URLs. This is for example done in the [ts-dev-gauge-googlecharts](https://github.com/TIBCOSoftware/spotfire-mods/blob/d2e3592106ea02aef1100b40f7c94b83e9545db3/examples/ts-dev-gauge-googlecharts/static/mod-manifest.json#L6) example to reach the google charts library.

There are some areas worth knowing when using external resources from a mod:
- A mod's iframe is sandboxed and therefore its `origin` header is `null` in any network requests it makes.
- Mods with external resources cannot be exported from the web client, due to security concerns. 

[Why is an external resource not loading correctly due to a content security policy?](https://tibcosoftware.github.io/spotfire-mods/docs/getting-started/#why-is-an-external-resource-not-loading-correctly-due-to-a-content-security-policy)
